spring.application.name=library-ai
spring.datasource.url=jdbc:h2:mem:library_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.ai.google.gemini.api-key=AQ.Ab8RN6LfY-Ubt-m0cFa4laSZ1maUHpa5aGKK6bRa_LeCwn9Pkg